# src/physics/run_worker_wrapper.py

"""
  Unified entry point for parallel execution via joblib.
  Acts as a dispatcher that routes the compute task to the appropriate
  physics generation engine (Hadronic or Quark) based on the task tuple.

Refactored:
  - Cleaned up documentation.
  - Explicit unpacking to prevent tuple index errors.
"""

from src.physics.worker_hadronic_gen import worker_hadronic_gen
from src.physics.worker_quark_gen import worker_quark_gen


import logging
from src.utils.exceptions import UnknownGenerationModeError

logger = logging.getLogger(__name__)

def run_worker_wrapper(task_tuple: tuple):
    """
    Dispatches the compute task to the specific physics generator.

    Parameters:
    - task_tuple: Tuple containing (mode, batch_size, seed, batch_idx).

    Returns:
    - List of valid star data points generated by the worker.
    """
    # unpack task metadata
    mode, batch_size, seed, batch_idx = task_tuple

    try:
        # dispatch to the correct physics engine
        if mode == "hadronic":
            # hadronic generation uses pure natural sampling
            return worker_hadronic_gen(batch_size, seed, batch_idx)
    
        elif mode == "quark":
            # quark generation is purely parametric (Generalized CFL)
            # it does not rely on the hadronic baselines
            return worker_quark_gen(batch_size, seed, batch_idx)
    
        else:
            raise UnknownGenerationModeError(mode)
    except Exception as e:
        logger.warning(f"Worker {mode} failed with exception: {e}")
        return None
