# src/physics/run_worker_wrapper.py

"""
  Unified entry point for parallel execution via joblib.
  Acts as a dispatcher that routes the compute task to the appropriate
  physics generation engine (Hadronic or Quark) based on the task tuple.

Refactored:
  - Cleaned up documentation.
  - Dispatches deterministic batches of shared amplitude sweep points.
"""

from src.physics.worker_hadronic_gen import worker_hadronic_gen
from src.physics.worker_quark_gen import worker_quark_gen


from src.utils.exceptions import UnknownGenerationModeError

def run_worker_wrapper(task_tuple: tuple):
    """
    Dispatches the compute task to the specific physics generator.

    Parameters:
    - task_tuple: Tuple containing (mode, sweep_points, batch_idx).

    Returns:
    - List of valid star data points generated by the worker.
    """
    # unpack task metadata
    mode, sweep_points, batch_idx = task_tuple

    if mode == "hadronic":
        return worker_hadronic_gen(sweep_points, batch_idx)
    if mode == "quark":
        return worker_quark_gen(sweep_points, batch_idx)
    raise UnknownGenerationModeError(mode)
