# src/config.py

"""
Centralized configuration dictionary for Physics limits, Macroscopic constraints,
Machine Learning features, and Plotting boundaries.
"""

CONFIG = {
    # ==========================================
    # 1. FUNDAMENTAL PHYSICS & UNITS
    # ==========================================
    "HC": 197.33,
    "M_N": 939.0,
    "G_CONV": 1.124e-5,
    "A_CONV": 1.4766,
    "P_C1": 9.34375e-5,
    "P_C2": 4.1725e-8,
    "P_C3": 1.44875e-11,
    "P_TRANS_DEFAULT": 0.184,
    "M_MIN_SAVE": 0.1,
    "M_MAX_LOWER_BOUND": 2.08,
    "H_M_MAX_UPPER": 3.0,
    "Q_M_MAX_UPPER": 3.0,
    "Q_R_MAX": 30.0,
    "CAUSALITY_EPS_LIMIT": 1000.0,
    "BUCHDAHL_LIMIT": 4.0 / 9.0,
    "BH_LIMIT": 0.5,
    "HADRONIC_P_CEFT_RANGE": (2.0, 15.0),
    "HADRONIC_WINDOW_WIDTH_MOD": 0.1,
    "HADRONIC_EPS_MAX": 4000.0,
    "HADRONIC_NUM_NODES_RANGE": (2, 6),
    "Q_B_MIN": 57.0,
    "Q_B_ABS_MAX": 400.0,
    "Q_DELTA_RANGE": (57.0, 250.0),
    "Q_MS_RANGE": (80.0, 120.0),
    "OBS_R14_HADRONIC_MAX": 14.5,
    "OBS_R14_HADRONIC_MIN": 9.5,
    "OBS_R14_QUARK_MAX": 14.5,
    "OBS_R14_QUARK_MIN": 8.5,
    "Q_B_MAX_COEFF": 55.0,
    "Q_B_MAX_SLOPE": 0.002,
    "CS2_DENOMINATOR_LIMIT": 1e-10,
    "PHYSICAL_FILTER_M_MIN": 0.5,
    "PHYSICAL_FILTER_R_MIN": 5.0,
    "EOS_NODE_MIN_SEP": 100.0,
    "PERTURB_AMP_RANGE": [-0.4, 0.4],
    "PERTURB_LOC_RANGE": [300.0, 1200.0],
    "PERTURB_WIDTH_RANGE": [50.0, 300.0],
    "GAUSSIAN_AMP_RANGE": [-0.1, 0.1],
    "GAUSSIAN_SIGMA_RANGE": [20.0, 120.0],
    "THERMO_FLOOR": 0.01,
    "P_GRID_MAX": 2500.0,
    "P_GRID_POINTS": 10000,
    "DYNAMIC_SEARCH_MAX": 10.0,
    "DYNAMIC_SEARCH_POINTS": 100,
    "ATTEMPT_MULTIPLIER": 5000,
    "MIN_MASS_CUTOFF": 0.05,
    "MIN_RADIUS_CUTOFF": 3.0,
    "ABSOLUTE_P_MAX_FALLBACK": 10**4.2,

    # ==========================================
    # 2. SOLVER SETTINGS
    # ==========================================
    "TOV_R_MIN": 1e-4,
    "TOV_R_MAX": 500.0,
    "TOV_P_MIN_SAFE": 1e-14,
    "GRID_P_MIN_LOG": 1e-14,
    "GRID_P_TRANSITION": 1.0,
    "GRID_P_MAX_LIN": 4000.0,
    "GRID_CRUST_POINTS": 300,
    "GRID_CORE_POINTS": 1200,
    "SMALL_STEP_M": 1e-5,
    "ODE_RTOL": 1e-10,
    "ODE_ATOL": 1e-12,
    "TOV_RTOL": 1e-8,
    "TOV_ATOL": 1e-10,
    "SOLVER_N_POINTS": 200,
    "SOLVER_N_LOW_RATIO": 0.3,
    "DENSE_PROFILES_POINTS": 300,
    "SURFACE_PRESSURE_EVENT_CUTOFF": 1e-13,
    "TOV_SINGULARITY_LIMIT": 1e-5,
    "TOV_CENTER_R_LIMIT": 1e-4,

    # ==========================================
    # 3. ML SETTINGS
    # ==========================================
    "ML_XGB_N_ESTIMATORS_RANGE": (50, 1000),
    "ML_XGB_MAX_DEPTH_RANGE": (3, 12),
    "ML_XGB_LR_RANGE": (1e-4, 0.5),
    "ML_XGB_SUBSAMPLE_RANGE": (0.5, 1.0),
    "ML_XGB_COLSAMPLE_RANGE": (0.6, 1.0),
    
    "ML_LGB_N_ESTIMATORS_RANGE": (50, 1000),
    "ML_LGB_MAX_DEPTH_RANGE": (3, 12),
    "ML_LGB_LR_RANGE": (1e-4, 0.5),
    "ML_LGB_SUBSAMPLE_RANGE": (0.5, 1.0),

    "ML_BNN_N_LAYERS_RANGE": (1, 5),
    "ML_BNN_N_UNITS_RANGE": (16, 256),
    "ML_BNN_KL_WEIGHT_RANGE": (1e-6, 1.0),
    "ML_BNN_LR_INIT_RANGE": (1e-5, 1e-1),
    "ML_BNN_DEFAULT_HIDDEN_LAYERS": (64, 32),
    "ML_BNN_DEFAULT_LR_INIT": 1e-3,
    "ML_BNN_DEFAULT_MAX_ITER": 300,
    "ML_BNN_DEFAULT_KL_WEIGHT": 1.0,
    "ML_BNN_MC_SAMPLES_TRAIN": 1,
    "ML_BNN_MC_SAMPLES_TEST": 30,
    "ML_BNN_BATCH_SIZE": 8192,
    "ML_BNN_PATIENCE": 5,
    "ML_BNN_WEIGHT_PRIOR_RANGE": (-0.2, 0.2),
    "ML_BNN_RHO_PRIOR_RANGE": (-5.0, -4.0),
    
    "ML_ISO_FOREST_CONTAMINATION": 0.01,
    "ML_CV_SPLITS": 5,
    "ML_RANDOM_SEED": 42,
    "ML_HPO_TRIALS": 150,
    "ML_CONFORMAL_ALPHA": 0.05,
    "ML_HPO_SUBSAMPLE_SIZE": 25000,
    "ML_MAX_ITER_TUNE": 30,
    "ML_MAX_ITER_FINAL": 50,
    "ML_MAX_ITER_ABLATION": 30,
    "ML_N_MC_SAMPLES_TRAIN_PIPELINE": 2,
    "ML_AUDIT_MASS_BINS": [1.1, 1.6, 2.1, 4.0],

    # ==========================================
    # 4. DATA SCHEMA
    # ==========================================
    "COLUMN_SCHEMA": [
        "Mass", "Radius", "Lambda", "Label", "Curve_ID",
        "P_Central", "Eps_Central", "Eps_Surface", "CS2_Central",
        "CS2_at_14", "Radius_14", "Slope14", "Slope16", "Slope18", "Slope20",
        "Bag_B", "Gap_Delta", "Mass_Strange", "Generation_Seed",
        "Perturb_A", "Perturb_eps0", "Perturb_sigma", "Baseline_Name"
    ],
    "ML_FEATURES": {
        "Geo": ["Mass", "Radius"],
        "A": ["Mass", "Radius", "LogLambda"],
        "B": ["Mass", "Radius", "LogLambda", "Eps_Central"],
        "C": ["Mass", "Radius", "LogLambda", "Eps_Central", "CS2_Central"],
        "D": ["Mass", "Radius", "LogLambda", "Eps_Central", "CS2_Central", "Slope14"],
    },
    
    # ==========================================
    # 5. PATHS
    # ==========================================
    "DATA_DIR": "data",
    "MODELS_DIR": "models",
    "PLOTS_DIR": "plots",
    "PHYSICS_TEST_DATASET": "data/physics_test_dataset.parquet",
    "ML_MODELS_GEO_A": "models/ml_models_geo_A.pkl",
    "ML_STUDY_XGBOOST": "models/study_xgboost_{model_name}.pkl",
    "ML_STUDY_XGB": "models/study_xgb_{model_name}.pkl",
    "ML_STUDY_LIGHTGBM": "models/study_lightgbm_{model_name}.pkl",
    "ML_STUDY_LGBM": "models/study_lgbm_{model_name}.pkl",
    "ML_STUDY_MLP": "models/study_mlp_{model_name}.pkl",
    "PLOT_ABLATION_MATRIX": "plots/fig_feature_ablation_matrix.pdf",
    "PLOT_ML_ROC_PR": "plots/fig_ml_roc_pr.pdf",
    "PLOT_ML_CALIBRATION": "plots/fig_ml_calibration.pdf",
    "PLOT_ML_ACCURACY_VS_MASS": "plots/fig_ml_accuracy_vs_mass.pdf",
    "PLOT_ML_FEATURE_IMPORTANCE": "plots/fig_ml_feature_importance.pdf",
    "PLOT_ML_CORR": "plots/fig_ml_corr_{model_name}_{tag}.pdf",
    "PLOT_ML_SHAP_BEESWARM": "plots/fig_ml_shap_beeswarm_{model_name}.pdf",
    "PLOT_ML_LEARNING_CURVE": "plots/fig_ml_learning_curve_{model_name}.pdf",
    "PLOT_ML_NOISE_ROBUSTNESS": "plots/fig_ml_noise_robustness.pdf",
    "PLOT_ML_EPISTEMIC_UNCERTAINTY": "plots/fig_ml_epistemic_uncertainty_{model_name}.pdf",
    "PLOT_CORE_MR": "plots/fig_core_mr.pdf",
    "PLOT_CORE_LAMBDA_M": "plots/fig_core_lambda_m.pdf",
    "PLOT_CORE_LAMBDA_R": "plots/fig_core_lambda_r.pdf",
    "PLOT_PHYSICS_CS2_VS_PRESSURE": "plots/fig_physics_cs2_vs_pressure.pdf",
    "PLOT_PHYSICS_EOS_BANDS": "plots/fig_physics_eos_bands.pdf",
    "PLOT_PHYSICS_MASS_VS_RHO": "plots/fig_physics_mass_vs_rho.pdf",
    "BANDS_AND_PATHS": {
        "MDI-1": "data/MDI-1.txt",
        "MDI-2": "data/MDI-2.txt",
        "MDI-3": "data/MDI-3.txt",
        "MDI-4": "data/MDI-4.txt",
        "NLD": "data/NLD.txt",
        "HHJ-1": "data/HHJ-1.txt",
        "HHJ-2": "data/HHJ-2.txt",
        "Ska": "data/Ska.txt",
        "SkI4": "data/SkI4.txt",
        "HLPS-2": "data/HLPS-2.txt",
        "HLPS-3": "data/HLPS-3.txt",
        "SCVBB": "data/SCVBB.txt",
        "WFF-1": "data/WFF-1.txt",
        "WFF-2": "data/WFF-2.txt",
        "PS": "data/PS.txt",
        "W": "data/W.txt",
        "BGP": "data/BGP.txt",
        "BL-1": "data/BL-1.txt",
        "BL-2": "data/BL-2.txt",
        "DH": "data/DH.txt",
        "APR-1": "data/APR-1.txt"
    },

    # ==========================================
    # 6. VISUALIZATION LIMITS
    # ==========================================
    "PLOT_R_LIM": (5.0, 20.0),
    "PLOT_M_LIM": (0.0, 4.0),
    "PLOT_L_LIM": (0.0, 5.0),
    "PLOT_EPS_LIM": (0, 2500),
    "PLOT_EPS_LOG": (1e2, 5e3),
    "PLOT_CS2_LIM": (0, 1.05),
    "PLOT_SLOPE_LIM": (-8, 6),
    "BUCHDAHL_FACTOR": 2.25,
}
